name: '[CN]添加服务器卡片到主页'
description: '我们只需要服务器的一些必要信息，注意: 未正确根据提示发送申请可能会被忽略或关闭.'
title: '[添加服务器]: 此处填写服务器名称..'
labels: ["Submit", "Lang:CN"]
body:
  - type: markdown
    id: Info
    attributes:
      value: |
        您只需要提供服务器的一些必要信息。

  - type: input
    id: contact
    attributes:
      label: '服务器名称'
      description: '您的服务器叫什么？'
      placeholder: 'ex. Minecraft服务器'
    validations:
      required: true

  - type: input
    id: ip
    attributes:
      label: '服务器地址'
      description: '您的服务器地址是什么？'
      placeholder: 'ex. mc.testserver.com:25565'
    validations:
      required: true

  - type: textarea
    id: server-motd
    attributes:
      label: '您的服务器描述'
      description: '使用简短的语言描述您的服务器，控制在 50 字以内为宜。'
      placeholder: '服务器描述'
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: '版本'
      description: 'Java/基岩/互通'
      options:
        - 'Java'
        - '基岩'
        - '互通'
      default: 0
    validations:
      required: true

  - type: dropdown
    id: Language
    attributes:
      label: '语言'
      description: '服务器语言'
      options:
        - 'zh_CN'
        - 'en'
        - 'ru'
      default: 0
    validations:
      required: true

  - type: dropdown
    id: auth_mode
    attributes:
      label: '认证方式'
      description: '可选offline(离线服务器)，yggdrasil(外置登录)，official(正版服务器)'
      options:
        - 'offline'
        - 'yggdrasil'
        - 'official'
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: is_member
    attributes:
      label: 服务器是否加入了MSCPO组织（需在服务器群聊或宣传网页中注明MSCPO,具有明确的指向MSCPO的链接）
      description: 服务器是否加入了MSCPO组织，如果是MSCPO的成员，服务器卡片将添加“认证服务器”标签
      options:
        - label: 服务器是否加入了MSCPO组织
          required: false

  - type: textarea
    id: server-version
    attributes:
      label: '具体客户端版本'
      description: '客户端的版本'
      placeholder: 'ex. 1.8.2-1.20.4'
    validations:
      required: true

  - type: textarea
    id: server-link
    attributes:
      label: '服务器宣传链接'
      description: '服务器的宣传链接，可以是服务器官网（宣传页面），服务器宣传视频链接，又或者是服务器群聊入群链接，用于服务器卡牌链接跳转'
      placeholder: 'https://'
    validations:
      required: true

  - type: textarea
    id: server-icon
    attributes:
      label: '您的服务器图标链接'
      description: '您的服务器图标链接（可选）'
      placeholder: 'https://'
    validations:
      required: false
